/**
 * Tree-sitter adapter exports — re-exports from vendored pi-tree-sitter.
 *
 * Generated by build-adapters.mjs — do not edit manually.
 * Vendor files are excluded from typecheck; this module provides
 * the clean import point for the adapter.
 */

// Re-export from vendored pi-tree-sitter
export {
  lineAt,
  formatError,
  collectErrors,
  MAX_ERRORS,
  CLOSER_LABELS,
} from "./vendor/index.js";
