/**
 * Type declarations for vendored pi-tree-sitter exports.
 * Generated by build-adapters.mjs — do not edit manually.
 */
import type { Tree, Node as TSNode } from "web-tree-sitter";

export declare const MAX_ERRORS: number;
export declare const CLOSER_LABELS: Record<string, string>;
export declare function lineAt(source: string, offset: number): string;
export declare function formatError(node: TSNode, source: string): string;
export declare function collectErrors(tree: Tree, source: string): string[];
